### ISSUE TITLE
A Few Cheater Groups

### ISSUE THREAD

**Issue by Newportt1** [d3fc0n6/CheaterList#1]
I found these by looking at the profiles of admins of known cheater groups, those admins are either in or admins in these groups as well. I started with this group https://steamcommunity.com/groups/lmaoboxhackerz/members.

DoesHotter Alts: https://steamcommunity.com/groups/DoesHotterAccounts

HVH group: https://steamcommunity.com/groups/Tboosting

Anti BD group: https://steamcommunity.com/groups/antipazerfags

Engiehook: https://steamcommunity.com/groups/OfficialEngineerINC

cathook:           https://steamcommunity.com/groups/cathook

myg0t: https://steamcommunity.com/groups/My-g0t

**Comment by d3fc0n6** [comment]
Went ahead and added these, Thanks!
