### ISSUE TITLE
Few More Cheat Groups

### ISSUE THREAD

**Issue by Newportt1** [d3fc0n6/CheaterList#2]
Used The Same method as last time but used a cheater that was in the TF2DB trusted list and this cheater list instead of group to start.

Anti TF2BD- https://steamcommunity.com/groups/Anti-dBs

https://steamcommunity.com/groups/professionalklownsquad

HVH https://steamcommunity.com/groups/elitefortresstwo

https://steamcommunity.com/groups/jadensmithdll

https://steamcommunity.com/groups/hittinpp

https://steamcommunity.com/groups/HvH-teacher

https://steamcommunity.com/groups/ExMarineHittingP

**Comment by d3fc0n6** [comment]
Added a few of those. A few of those such as ExMarineHittingP is that there may be a large amount of false positives. Either way thanks for the list!
